POST http://localhost:8000/api/users
Content-Type: application/json
Accept-Language: en-US,en;q=0.5

{
    "email": "lubsanis@gmail.com",
    "firstName": "Eduardo",
    "lastName": "Raymondi",
    "phone": "99887766",
    "role": "DRIVER",
    "rawPassword": "inicio123"
}
###
GET http://localhost:8000/api/users/19ae91c4-1c65-4988-a22a-cfcf849900b3
Content-Type: application/json
Accept-Language: en-US,en;q=0.5
###
GET http://localhost:8000/api/users
Content-Type: application/json
Accept-Language: en-US,en;q=0.5
###
